services:
  - type: web
    name: planner2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    hooks:
      preDeploy: alembic -c migrations/alembic.ini upgrade head 