"""add_picked_up_at_to_production_plans

Revision ID: 58a6439cd211
Revises: e6e49c5d0506
Create Date: 2025-11-25 11:48:39.924362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a6439cd211'
down_revision = 'e6e49c5d0506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_plans', schema=None) as batch_op:
        batch_op.drop_column('picked_up_at')

    # ### end Alembic commands ###

