"""add_allergen_types_and_update_raw_material_types

Revision ID: d1234567890b
Revises: c1234567890a
Create Date: 2025-01-20 16:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1234567890b'
down_revision = 'c1234567890a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу allergen_types
    op.create_table('allergen_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergen_types_id'), 'allergen_types', ['id'], unique=False)
    op.create_index(op.f('ix_allergen_types_name'), 'allergen_types', ['name'], unique=True)
    
    # Добавляем поле allergen_type_id в raw_material_types
    op.add_column('raw_material_types', sa.Column('allergen_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_raw_material_types_allergen_type_id', 'raw_material_types', 'allergen_types', ['allergen_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем внешний ключ и поле
    op.drop_constraint('fk_raw_material_types_allergen_type_id', 'raw_material_types', type_='foreignkey')
    op.drop_column('raw_material_types', 'allergen_type_id')
    
    # Удаляем таблицу allergen_types
    op.drop_index(op.f('ix_allergen_types_name'), table_name='allergen_types')
    op.drop_index(op.f('ix_allergen_types_id'), table_name='allergen_types')
    op.drop_table('allergen_types')
    # ### end Alembic commands ###
