"""add_many_to_many_allergens

Revision ID: e1234567890c
Revises: d1234567890b
Create Date: 2025-01-20 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1234567890c'
down_revision = 'd1234567890b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем промежуточную таблицу
    op.create_table('raw_material_type_allergens',
    sa.Column('raw_material_type_id', sa.Integer(), nullable=False),
    sa.Column('allergen_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_type_id'], ['allergen_types.id'], ),
    sa.ForeignKeyConstraint(['raw_material_type_id'], ['raw_material_types.id'], ),
    sa.PrimaryKeyConstraint('raw_material_type_id', 'allergen_type_id')
    )
    
    # Переносим существующие данные из allergen_type_id в новую таблицу
    op.execute("""
        INSERT INTO raw_material_type_allergens (raw_material_type_id, allergen_type_id)
        SELECT id, allergen_type_id 
        FROM raw_material_types 
        WHERE allergen_type_id IS NOT NULL
    """)
    
    # Удаляем старое поле allergen_type_id
    op.drop_constraint('fk_raw_material_types_allergen_type_id', 'raw_material_types', type_='foreignkey')
    op.drop_column('raw_material_types', 'allergen_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем обратно поле allergen_type_id
    op.add_column('raw_material_types', sa.Column('allergen_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_raw_material_types_allergen_type_id', 'raw_material_types', 'allergen_types', ['allergen_type_id'], ['id'])
    
    # Переносим данные обратно (берем первый аллерген для каждого вида сырья)
    op.execute("""
        UPDATE raw_material_types 
        SET allergen_type_id = (
            SELECT allergen_type_id 
            FROM raw_material_type_allergens 
            WHERE raw_material_type_allergens.raw_material_type_id = raw_material_types.id 
            LIMIT 1
        )
    """)
    
    # Удаляем промежуточную таблицу
    op.drop_table('raw_material_type_allergens')
    # ### end Alembic commands ###
