"""add_production_date_to_production_batches

Revision ID: g1234567890e
Revises: 1ad6e57cbc58
Create Date: 2025-01-20 19:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'g1234567890e'
down_revision = '1ad6e57cbc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_batches', sa.Column('production_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_batches', 'production_date')
    # ### end Alembic commands ###
