"""add_halal_status_to_raw_material_types

Revision ID: h1234567890f
Revises: g1234567890e
Create Date: 2025-01-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h1234567890f'
down_revision = 'g1234567890e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаём тип Enum для PostgreSQL
    halalstatus_enum = sa.Enum('haram', 'halal', 'not_specified', name='halalstatus')
    halalstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Добавляем колонку halal_status в таблицу raw_material_types
    op.add_column('raw_material_types', sa.Column('halal_status', halalstatus_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_material_types', 'halal_status')
    # Удаляем тип Enum
    op.execute('DROP TYPE IF EXISTS halalstatus')
    # ### end Alembic commands ###

