"""add_mass_control_to_raw_material_types

Revision ID: i1234567890g
Revises: h1234567890f
Create Date: 2025-01-21 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'i1234567890g'
down_revision = 'h1234567890f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку mass_control как VARCHAR (String)
    op.add_column('raw_material_types', sa.Column('mass_control', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_material_types', 'mass_control')
    # ### end Alembic commands ###

